### ISSUE TITLE
in 0.3.3 React is undefined at build time

### ISSUE THREAD

**Issue by joelhooks** [ChristopherBiscardi/gatsby-mdx#253]
**Describe the bug**
With 0.3.3 I'm also experiencing React not being defined. This is mentioned in #249 as well, but that presents a specific use case for failure and the problem seems farther spread than that.

Only affects build not develop

**To Reproduce**
[egghead blog starter](https://github.com/eggheadio/gatsby-starter-egghead-blog) and Steps to reproduce the behavior:
1. `gatsby build`

**Expected behavior**
It should build without error

**Additional context**
stack trace:

```
success Building production JavaScript and CSS bundles — 4.890 s
success Building static HTML for pages — 1.624 s — 9/9 27.32 pages/second
[ 'ReferenceError: __WEBPACK_EXTERNAL_MODULE_react__ is not defined\n    at Object.react (evalmachine.<anonymous>:2699:18)\n    at __webpack_require__ (evalmachine.<anonymous>:20:30)\n    at Module../node_modules/@emotion/core/dist/core.esm.js (evalmachine.<anonymous>:535:63)\n    at __webpack_require__ (evalmachine.<anonymous>:20:30)\n    at Module../node_modules/gatsby-mdx/utils/wrap-root-render-html-entry.js (evalmachine.<anonymous>:2624:71)\n    at __webpack_require__ (evalmachine.<anonymous>:20:30)\n    at evalmachine.<anonymous>:84:18\n    at evalmachine.<anonymous>:87:10\n    at Script.runInContext (vm.js:102:20)\n    at Script.runInNewContext (vm.js:108:17)' ]
error UNHANDLED EXCEPTION


  Error: no such file or directory

  - MemoryFileSystem.js:114 MemoryFileSystem.readFileSync
    [gatsby-starter-egghead-blog]/[memory-fs]/lib/MemoryFileSystem.js:114:10

  - render-html.js:54 compiler.run
    [gatsby-starter-egghead-blog]/[gatsby-mdx]/utils/render-html.js:54:26

  - Compiler.js:210 finalCallback
    [gatsby-starter-egghead-blog]/[webpack]/lib/Compiler.js:210:39

  - Compiler.js:259 hooks.done.callAsync.err
    [gatsby-starter-egghead-blog]/[webpack]/lib/Compiler.js:259:14


  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [gatsby-starter-egghead-blog]/[tapable]/lib/Hook.js:154:20

  - Compiler.js:257 emitRecords.err
    [gatsby-starter-egghead-blog]/[webpack]/lib/Compiler.js:257:22

  - Compiler.js:371 Compiler.emitRecords
    [gatsby-starter-egghead-blog]/[webpack]/lib/Compiler.js:371:39

  - Compiler.js:251 emitAssets.err
    [gatsby-starter-egghead-blog]/[webpack]/lib/Compiler.js:251:10

  - Compiler.js:357 hooks.afterEmit.callAsync.err
    [gatsby-starter-egghead-blog]/[webpack]/lib/Compiler.js:357:14


  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [gatsby-starter-egghead-blog]/[tapable]/lib/Hook.js:154:20

  - Compiler.js:354 asyncLib.forEach.err
    [gatsby-starter-egghead-blog]/[webpack]/lib/Compiler.js:354:27

  - async.js:2825
    [gatsby-starter-egghead-blog]/[neo-async]/async.js:2825:7

  - async.js:2861 done
    [gatsby-starter-egghead-blog]/[neo-async]/async.js:2861:11

  - async.js:2813
    [gatsby-starter-egghead-blog]/[neo-async]/async.js:2813:7

  - MemoryFileSystem.js:328 MemoryFileSystem.writeFile
    [gatsby-starter-egghead-blog]/[memory-fs]/lib/MemoryFileSystem.js:328:9

  - Compiler.js:338 writeOut
    [gatsby-starter-egghead-blog]/[webpack]/lib/Compiler.js:338:29

  - Compiler.js:348 asyncLib.forEach
    [gatsby-starter-egghead-blog]/[webpack]/lib/Compiler.js:348:7

  - async.js:2416 baseEach
    [gatsby-starter-egghead-blog]/[neo-async]/async.js:2416:9

  - async.js:2850 Object.each
    [gatsby-starter-egghead-blog]/[neo-async]/async.js:2850:9

  - Compiler.js:311 emitFiles
    [gatsby-starter-egghead-blog]/[webpack]/lib/Compiler.js:311:13
```

**Comment by ChristopherBiscardi** [comment]
This is caused by the `html` query in the [gatsby-plugin-feed config](https://github.com/eggheadio/gatsby-starter-egghead-blog/blob/56ab62bc12f8ec1e9dbd13ec5c80694aa92e3687/gatsby-config.js#L112).

I was working on this last night but haven't made substantial progress yet. It's my top priority to fix right now.

**Comment by ChristopherBiscardi** [comment]
I pushed some code to master that may have the fix here. Something was adding `React` to the webpack externals.

**Comment by joelhooks** [comment]
Thanks @ChristopherBiscardi 🙏
